#!/bin/env bash

# Function to display usage
usage() {
	    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	        exit 1
	}

# Check if less than 4 parameters are passed
if [ "$#" -ne 4 ]; then
	    usage
fi

# Assign parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
