#!/bin/bash

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default

nginx -s reload

update-rc.d nginx defaults

nginx -t

if ! pgrep nginx > /dev/null
then
    service nginx start
fi

