#!/usr/bin/env bash
# Check if the script is called with the correct number of arguments

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Get the IP address passed as an argument
ip_address=$1

# Ping the IP address 5 times and display the result
ping -c 5 "$ip_address"
