#!/usr/bin/env bash
# Iterate over the files in the current directory

for file in *; do
    if [ ! -h "$file" ] && [ -f "$file" ]; then
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_after_dash"
    fi
done
